hungups2-war/src/java/au/edu/uts/aip/hungups2/controller/ImageController.java
package au.edu.uts.aip.hungups2.controller;

import au.edu.uts.aip.hungups2.ejb.*;
import au.edu.uts.aip.hungups2.entity.Image;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import com.cloudinary.*;
import com.cloudinary.utils.*;
import java.io.*;
import java.net.Authenticator;
import java.net.PasswordAuthentication;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.validator.ValidatorException;
import javax.faces.view.ViewScoped;
import javax.servlet.http.Part;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import org.apache.commons.io.IOUtils;
import org.cloudinary.json.JSONObject;

/**
 * This ImageController is for CRUD operation of image
 *
 * @author Yihao Jiang
 */
@Named
@ViewScoped
public class ImageController implements Serializable {

    @EJB
    private ImageBean imageBean;

    private Image image = new Image();
    private Part imageFile;
    private static final String API_KEY = "834717547222136";
    private static final String API_SECRET = "FeGAbxLTcfMYJWcmjFBbKS1Qjm4";
    private static final String CLOUD_NAME = "jyh1991";

    public Image getImage() {
        return image;
    }

    public Part getImageFile() {
        return imageFile;
    }

    public void setImageFile(Part imageFile) {
        this.imageFile = imageFile;
    }

    /**
     * Calls the EJB imageBean to find the image by its id from the database
     *
     * @param id the image id looking for
     */
    public void loadImageById(int id) {
        image = imageBean.findImage(id);
    }

    /**
     * Calls the EJB to retrieve all the images from the database
     *
     * @return a collection of all the images in the database
     */
    public List<Image> getAllImages() {
        return imageBean.findAll();
    }

    /**
     * Upload the imageFile that is submitted from the JSF page to Cloudinary
     *
     * @return redirection to the main page
     */
    public String uploadNewImage() {
        // Create cloudinary link
        Cloudinary cloudinary = new Cloudinary(ObjectUtils.asMap(
                "cloud_name", CLOUD_NAME,
                "api_key", API_KEY,
                "api_secret", API_SECRET));
        Map uploadResult;
        try {
            // Try to upload and retrieve an result
            uploadResult = cloudinary.uploader().upload(
                    IOUtils.toByteArray(imageFile.getInputStream()),
                    ObjectUtils.emptyMap());
        } catch (IOException ex) {
            Logger.getLogger(ImageController.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
        // set the image url to the image object
        image.setUrl((String) uploadResult.get("url"));
        String currentUser = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().toString();
        // calls the EJB to update the image url and the upload user in the database
        imageBean.uploadImage(image, currentUser);
        return "index?faces-redirect=true";
    }

    /**
     * Calls the EJB to Update the details of an image in the database
     *
     * @return redirection to the manage image page
     */
    public String updateImage() {

        // For normal users, check image owner
        if (FacesContext.getCurrentInstance().getExternalContext().isUserInRole("Users")) {
            String username = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().toString();
            if (image.getAccount().getUsername().equals(username)) {
                imageBean.updateImage(image);
                return "manage_image?faces-redirect=true";
            }
            // For administrator
        } else if (FacesContext.getCurrentInstance().getExternalContext().isUserInRole("Admins")) {
            imageBean.updateImage(image);
            return "admin_manage?faces-redirect=true";
        }
        return "index?faces-redirect=true";
    }

    /**
     * Calls the EJB to delete the image from the database
     *
     * @return redirection to the manage image page
     */
    public String deleteImage() {

        // For normal users, check image owner
        if (FacesContext.getCurrentInstance().getExternalContext().isUserInRole("Users")) {
            String username = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().toString();
            if (image.getAccount().getUsername().equals(username)) {
                imageBean.deleteImage(image);
                return "manage_image?faces-redirect=true";
            }
            // For administrator
        } else if (FacesContext.getCurrentInstance().getExternalContext().isUserInRole("Admins")) {
            imageBean.deleteImage(image);
            return "admin_manage?faces-redirect=true";
        }
        return "index?faces-redirect=true";
    }

    /**
     * Check if the image is the correct size Check if the uploaded file is an
     * image
     *
     * @param context
     * @param component
     * @param obj
     */
    public void imageValidate(FacesContext context, UIComponent component, Object obj) {
        Part file = (Part) obj;
        // Check if there is something uploaded
        if (file == null) {
            throw new ValidatorException(new FacesMessage("Please select image"));
        }
        // Check if the file size is correct
        if (file.getSize() > 4000000) {
            throw new ValidatorException(new FacesMessage("Uploaded image is too large"));
        }
        // Check if it is an image
        if ((!"image/jpeg".equals(file.getContentType()))
                && (!"image/bmp".equals(file.getContentType()))
                && (!"image/png".equals(file.getContentType()))) {
            throw new ValidatorException(new FacesMessage("Uploaded file is not image"));
        }
    }

    /**
     * Retrieve Cloudinary information for uploading images
     * @return 
     */
    public String getCloudinaryInformation() {

        Authenticator.setDefault(new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("834717547222136", "FeGAbxLTcfMYJWcmjFBbKS1Qjm4".toCharArray());
            }
        });
        Client client = ClientBuilder.newClient();
        WebTarget adminResource = client.target("https://api.cloudinary.com/v1_1/jyh1991/usage");
        Invocation.Builder builder = adminResource.request(MediaType.TEXT_PLAIN);
        String result = builder.get(String.class);
        JSONObject resultJson = new JSONObject(result);

        JSONObject transformations = (JSONObject) resultJson.get("transformations");
        JSONObject images = (JSONObject) resultJson.get("objects");
        JSONObject bandwidth = (JSONObject) resultJson.get("bandwidth");
        JSONObject storage = (JSONObject) resultJson.get("storage");

        StringBuffer info = new StringBuffer();
        info.append("Transformations: ").append(transformations.get("used_percent")).append("%\n  ")
                .append("Images: ").append(images.get("used_percent")).append("%\n  ")
                .append("Bandwidth: ").append(bandwidth.get("used_percent")).append("%\n  ")
                .append("Storage: ").append(storage.get("used_percent")).append("%\n  ");

        return info.toString();
    }
}

hungups2-war/web/activation.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Activation</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body>
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <h:panelGroup class="wrapper" layout="block">

            <h:outputText rendered="#{accountController.activate(param.username, param.hash)}" 
                          value="Congratulations! You have successfully activated your account!"/>

        </h:panelGroup>    
        <h:outputScript library="js" name="jquery-3.1.1.min.js" />
        <h:outputScript library="js" name="sticky-header.js" />
    </h:body>
</html>


hungups2-war/web/admin_information.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Manage your images!</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body class="sticky-header">
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <div class="wrapper">
            <section>
                <h2>Cloudinary usage:</h2>
                #{imageController.cloudinaryInformation}
            </section>
        </div>    

    </h:body>
</html>

hungups2-war/web/admin_manage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Manage your images!</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body class="sticky-header">
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <div class="wrapper">
            <table class="catalogue">
                <tbody>
                    <tr>
                        <ui:repeat var="image" value="#{imageController.allImages}" varStatus="status">
                        <td class="catalogbox">
                            <h:link class="catalogue" outcome="image_detail">
                            <f:param name="index" value="#{image.id}" />
                                <section>
                                    <h:graphicImage value="#{image.url}" class="cata_thumb" alt="thumb" />
                                    <h3 class="catalogue">#{image.title}</h3>
                                    <h:link value="Edit " outcome="edit_image">
                                        <f:param name="index" value="#{image.id}" />
                                    </h:link>
                                    <h:link value="Delete" outcome="delete_image">
                                        <f:param name="index" value="#{image.id}" />
                                    </h:link>
                                </section>
                            </h:link>
                        </td>
                        <h:outputText value="&lt;/tr&gt;&lt;tr&gt;" escape="false" rendered="#{status.index%3==2}" />  
                    </ui:repeat>
                    </tr>
                </tbody>
            </table>
            <section><h2><h:link value="Check Cloudinary status" outcome="admin_information" /></h2></section>
        </div>    

    </h:body>
</html>

hungups2-war/web/edit_image.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" >
    <f:metadata>
        <f:viewAction action="#{imageController.loadImageById(param.index)}"/>
    </f:metadata>
    <h:head>
        <title>Edit Image</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body class="sticky-header">
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <div class="wrapper">
            <section><h2>Edit your image information</h2></section>
            <section>
                <h3 class="imagebox">#{imageController.image.title}</h3>
                <div class="imagebox">
                    <h:graphicImage value="#{imageController.image.url}" class="small_image" alt="image" />
                </div>
                
                <br />
		<div class="imageInfo">
		<!--<h2> Upload new photo </h2>-->
                <br />
                <h:form id="uploadForm">
                    <h:panelGrid columns="2" class="submit_box">
                        <h:panelGroup>
                            <strong>Author: </strong>
                        </h:panelGroup>
                        <h:panelGroup>
                            <h3>#{imageController.image.account.username}</h3>
                        </h:panelGroup>

                        <h:panelGroup>
                            Title: 
                            <h:panelGroup class="compulsory">*</h:panelGroup>
                        </h:panelGroup>
                        <h:panelGroup>
                            <h:inputText id="title" value="#{imageController.image.title}"
                                         validatorMessage="Please input image title." />
                            <h:messages class="compulsory" for="title"/>
                        </h:panelGroup>

                        <h:panelGroup>Details: </h:panelGroup>
                        <h:panelGroup>
                            <h:inputTextarea id="details" value="#{imageController.image.details}" rows="8" cols="50" />
                            <h:messages class="compulsory" globalOnly="true"/>
                        </h:panelGroup>

                        <h:panelGroup></h:panelGroup>
                        <h:panelGroup>
                            <h:commandButton value="Submit" action="#{imageController.updateImage}"/>
                            &nbsp;&nbsp;
                            <h:button value="Cancel" outcome="manage_image"/>
                        </h:panelGroup>

                    </h:panelGrid>        
                </h:form>           
            </div>
            </section>	
        </div>    
        
    </h:body>
</html>

hungups2-war/web/forgot_password.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" 
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Forget Password</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body class="sticky-header">
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <h:panelGroup class="wrapper" layout="block">
            <section class="loginForm">
                <h:panelGroup class="imageInfo" layout="block">
                    <h2>Please enter your username and email</h2>
                    <h:form>
                        <h:panelGrid columns="2" class="submit_box">
                            <h:panelGroup>
                                Username: 
                                <h:panelGroup class="compulsory">*</h:panelGroup>
                            </h:panelGroup>
                            <h:panelGroup>
                                <h:inputText 
                                    id="username" 
                                    value="#{accountController.account.username}"
                                    validatorMessage="Please input your username." />
                                <h:messages class="compulsory" for="username"/>
                            </h:panelGroup>
                            <h:panelGroup>
                                Email: 
                                <h:panelGroup class="compulsory">*</h:panelGroup>
                            </h:panelGroup>
                            <h:panelGroup>
                                <h:inputText id="email" 
                                             value="#{accountController.account.email}"
                                             requiredMessage="Please enter your email address."
                                             validatorMessage="Invalid email format.">
                                    
                                    <f:validateRegex
                                    pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
                                </h:inputText>
                                <h:messages class="compulsory" for="email"/>
                            </h:panelGroup>
                        </h:panelGrid>
                        <h:messages globalOnly="true" class="compulsory"/>
                        <h:commandButton value="Send" action="#{accountController.sendResetPasswordEmail}"/>
                    </h:form>
                    <br />
                </h:panelGroup>
            </section>
        </h:panelGroup>  
    </h:body>
</html>


hungups2-war/web/image_detail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" >
    <f:metadata>
        <f:viewAction action="#{imageController.loadImageById(param.index)}"/>
    </f:metadata>
    <h:head>
        <title>Image</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body class="sticky-header">
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <div class="wrapper">
            <section>
                <h3 class="imagebox">#{imageController.image.title}</h3>
                <div class="imagebox">
                    <h:graphicImage value="#{imageController.image.url}" class="small_image" alt="image" />
                </div>
                
                <br />
                <div class="imageInfo">
                    <h3><strong>Author: </strong>#{imageController.image.account.username}</h3>
                    <p>
                        <h:outputText value="#{imageController.image.uploadDate}" >
                            <f:convertDateTime pattern="MM-dd-yyyy HH:mm" />
                        </h:outputText> 
                    </p>
                    <p>
                        #{imageController.image.details}
                    </p>
                </div>
            </section>
        </div>    
        <!--<h:outputScript library="js" name="jquery-2.1.1.min.js" />-->
        <!--<h:outputScript library="js" name="sticky-header.js" />-->
        <!--<h:outputScript library="js" name="comment-check.js" />-->
    </h:body>
</html>

hungups2-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Welcome!</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body>
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <h:panelGroup class="wrapper" layout="block">
            <table class="catalogue">
                <tbody>
                    <tr>
                        <ui:repeat var="image" value="#{imageController.allImages}" varStatus="status">
                            <td class="catalogbox">
                                <h:link class="catalogue" outcome="image_detail">
                                    <f:param name="index" value="#{image.id}" />
                                    <section>
                                        <h:graphicImage value="#{image.url}" class="cata_thumb" alt="thumb" />
                                        <h3 class="catalogue">#{image.title}</h3>
                                    </section>
                                </h:link>
                            </td>
                            <h:outputText value="&lt;/tr&gt;&lt;tr&gt;" escape="false" rendered="#{status.index%3==2}" />  
                        </ui:repeat>
                    </tr>
                </tbody>
            </table>
        </h:panelGroup>    
        <h:outputScript library="js" name="jquery-3.1.1.min.js" />
        <h:outputScript library="js" name="sticky-header.js" />
    </h:body>
</html>

hungups2-war/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" >
    <h:head>
        <title>Login</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body class="sticky-header">
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <h:panelGroup class="wrapper" layout="block">
            <section class="loginForm">
                <h:panelGroup class="imageInfo" layout="block">
                    <h2>Login</h2>
                    <h:form>
                        <h:panelGrid columns="2" class="submit_box">
                            <h:panelGroup>Username: </h:panelGroup>
                            <h:panelGroup>
                                <h:inputText 
                                    id="username" 
                                    value="#{accountController.account.username}"
                                    validatorMessage="Please input your username." 
                                    validator="#{accountController.validateLoginName}"/>
                                <h:messages for="username" class="compulsory"/>
                            </h:panelGroup>

                            <h:panelGroup>Password: </h:panelGroup>
                            <h:panelGroup>
                                <h:inputSecret 
                                    id="password" 
                                    value="#{accountController.account.password}"
                                    validatorMessage="Please input your password." />
                                <h:messages for="password" class="compulsory"/>
                            </h:panelGroup>
                        </h:panelGrid>
                        <h:messages globalOnly="true" class="compulsory"/>
                        <h:commandButton class="loginButton" value="Login" action="#{accountController.login}"/>&nbsp;&nbsp;
                        <h:button class="loginButton" value="Register" outcome="register"/>
                        <!--h:button value="Forgot Password" outcome="forgot_password"/-->
                    </h:form>
                </h:panelGroup>  
            </section>
        </h:panelGroup>    
    </h:body>
</html>

hungups2-war/web/logout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Logout...</title>
    </h:head>
    <h:body>
        <f:metadata>
            <f:viewParam name="username" value="#{request.userPrincipal}" />
            <f:viewAction action="#{accountController.logout}" />
        </f:metadata>
    </h:body>
</html>

hungups2-war/web/manage_image.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <f:metadata>
        <f:viewAction action="#{accountController.loadCurrentAccount}"/>
    </f:metadata>
    <h:head>
        <title>Manage your images!</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body class="sticky-header">
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <div class="wrapper">
	<table class="catalogue">
            <tbody>
                <tr>
                    <ui:repeat var="image" value="#{accountController.account.images}" varStatus="status">
                    <td class="catalogbox">
                        <h:link class="catalogue" outcome="image_detail">
                        <f:param name="index" value="#{image.id}" />
                            <section>
                                <h:graphicImage value="#{image.url}" class="cata_thumb" alt="thumb" />
                                <h3 class="catalogue">#{image.title}</h3>
                                <h:link value="Edit " outcome="edit_image">
                                    <f:param name="index" value="#{image.id}" />
                                </h:link>
                                <h:link value="Delete" outcome="delete_image">
                                    <f:param name="index" value="#{image.id}" />
                                </h:link>
                            </section>
                        </h:link>
                    </td>
                    <h:outputText value="&lt;/tr&gt;&lt;tr&gt;" escape="false" rendered="#{status.index%3==2}" />  
                </ui:repeat>
                </tr>
            </tbody>
                
        </table>
        </div>    

    </h:body>
</html>

hungups2-war/web/reset_password_email_sent.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Reset Password Email</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body>
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <h:panelGroup class="wrapper" layout="block">
            
            <h:outputText value="A password reset message has been sent to your registered email.
                          Please use the link provided to reset your password."/>
            
        </h:panelGroup>    
        <h:outputScript library="js" name="jquery-3.1.1.min.js" />
        <h:outputScript library="js" name="sticky-header.js" />
    </h:body>
</html>


hungups2-war/web/upload_image.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" >
    <h:head>
        <title>Upload new image!</title>
        <h:outputStylesheet library="css" name="style.css"  />
    </h:head>
    <h:body class="sticky-header">
        <header>
            <h1>Welcome To My Picture Gallery<br /></h1>
            <nav><ui:include src="/resources/navlink.xhtml" /></nav>
        </header>
        <h:panelGroup class="wrapper" layout="block">
            <section><h2>Upload your new image</h2></section>
            <section>
                <h:panelGroup class="imageInfo" layout="block">
                    <br />
                    <h:form id="uploadForm" enctype="multipart/form-data">
                        <h:panelGrid columns="2" class="submit_box">

                            <h:panelGroup>
                                Title: 
                                <h:panelGroup class="compulsory">*</h:panelGroup>
                            </h:panelGroup>
                            
                            <h:panelGroup>
                                <h:inputText id="title" value="#{imageController.image.title}"
                                             validatorMessage="Please input image title." />
                                <h:messages class="compulsory" for="title"/>
                            </h:panelGroup>
                            
                            <h:panelGroup>Details: </h:panelGroup>
                            <h:panelGroup>
                                <h:inputTextarea id="details" value="#{imageController.image.details}" rows="8" cols="50" />
                            </h:panelGroup>

                            <h:panelGroup>Select image </h:panelGroup>
                            <h:panelGroup>
                                <h:inputFile id="imageFile" value="#{imageController.imageFile}" validator="#{imageController.imageValidate}">
                                </h:inputFile>
                                <h:messages class="compulsory" for="imageFile"/>
                            </h:panelGroup>
                            
                            <h:panelGroup></h:panelGroup>
                            <h:panelGroup>
                                <h:commandButton value="Submit" action="#{imageController.uploadNewImage}"/> 
                            </h:panelGroup>

                        </h:panelGrid>        
                    </h:form>      
                </h:panelGroup>
            </section>	
        </h:panelGroup> 
    </h:body>
</html>